# Custom Language File for Launcher Customizer

[ejs.app]
title = "MCE Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/MCELSSS/MCELauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/MCELSSS/MCELauncher"
supportLink = "https://github.com/MCELSSS/MCELauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur MCE"
welcomeDescription = "soon."
welcomeDescCTA = "soon."
